export { default as Header } from './Header/Header';
export { default as Footer } from './Footer/Footer';
export { default as Loading } from './Loading/Loading';
export { default as Error } from './Error/Error';
export { default as CountriesTable } from './Table/CountriesTable';
export { default as PieChart } from './PieChart/PieChart';
export { default as MapDialog } from './PopUps/MapDialog';
export { default as FavMessage } from './PopUps/FavMessage';
export { default as CountryCard } from './Country/CountryCard'
